default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
    exclude: .*\.rs$
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
  - id: destroyed-symlinks
  - id: end-of-file-fixer
  # NOTE uncomment no-commit-to-branch once project gets underway
#      - id: no-commit-to-branch
  - id: pretty-format-json
    exclude: ^tree-sitter/(src/(grammar|node-types)|package)\.json$
  - id: trailing-whitespace
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
  - id: check-mailmap
  - id: forbid-binary
  - id: git-check
  - id: markdownlint
  - id: script-must-have-extension
  - id: script-must-not-have-extension
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.8.0
  hooks:
  - id: shellcheck
