[config]
default_to_workspace = false
skip_core_tasks = true
skip_crate_env_info = true
skip_git_env_info = true
skip_rust_env_info = true

[tasks.parser]
dependencies = ["generate-parser", "insta"]

[tasks.generate-parser]
cwd = "./compiler/chipc-ast/grammar"
command = "yarn"
args = ["generate"]

[tasks.insta]
command = "cargo"
args = ["insta", "test", "--review", "--package=chipc-ast"]
