[config]
default_to_workspace = false
skip_core_tasks = true
skip_crate_env_info = true
skip_git_env_info = true
skip_rust_env_info = true

[tasks.parser]
dependencies = ["generate-parser", "insta"]

[tasks.generate-parser]
install_crate = { crate_name = "tree-sitter-cli", binary = "tree-sitter", test_arg = "--help" }
cwd = "./compiler/chipc-ast"
command = "tree-sitter"
args = ["generate", "--no-bindings"]

[tasks.insta]
command = "cargo"
args = ["insta", "test", "--review", "--package=chipc-ast"]
