[package]
name = "chipc-main"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
chipc-ast = { path = "../chipc-ast" }
chipc-ast-lowering = { path = "../chipc-ast-lowering" }
chipc-codegen = { path = "../chipc-codegen" }
chipc-hir-lowering = { path = "../chipc-hir-lowering" }
