[package]
name = "chipc-mir"
version = "0.0.0"
edition = "2021"
publish = false

links = "chipc-mir"

[dependencies]
chipc-arena = { path = "../chipc-arena" }
cxx = "1.0.66"

[build-dependencies]
cxx-build = "1.0.66"
