[package]
name = "chipc-ast"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tree-sitter = "0.20.6"
tree-sitter-chip = { path = "../../tree-sitter" }

[dev-dependencies]
chip-snapshot-tests = { path = "../../tests/snapshot" }
